# Generated by Django 4.2.7 on 2023-12-04 16:44

from django.db import migrations, models
import user.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('surname', models.CharField(blank=True, max_length=250, null=True)),
                ('profile_image', models.TextField(blank=True, null=True)),
                ('referal_link', models.CharField(default=user.models.generate_random_string, editable=False, max_length=8, unique=True)),
                ('balance_usdt', models.FloatField(default=0.0)),
                ('balance_netbo', models.FloatField(default=0.0)),
                ('balance_btc', models.FloatField(default=0.0)),
                ('wallet_id_usdt', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('wallet_id_netbo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('wallet_id_btc', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_identified', models.BooleanField(default=False)),
                ('is_verified', models.IntegerField(blank=True, null=True)),
                ('is_archived', models.IntegerField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('balance_usdt', models.FloatField(default=0.0)),
                ('balance_netbo', models.FloatField(default=0.0)),
                ('balance_btc', models.FloatField(default=0.0)),
                ('created_at', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
    ]
